version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/devsite

hooks:
  AfterInstall:
    - location: scripts/fix_permissions.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/restart_apache.sh
      timeout: 300
      runas: root
