version: 0.2

phases:
  install:
    commands:
      - echo Installing...
  pre_build:
    commands:
      - echo Preparing artifacts...
  build:
    commands:
      - echo Build phase - nothing to compile
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - appspec.yaml
    - index.html
    - scripts/fix_permissions.sh
    - scripts/restart_apache.sh
  base-directory: .
