version: 0.2

env:
  variables:
    S3_BUCKET_NAME: "maheshs3-s3"

phases:
  pre_build:
    commands:
      - echo "🔍 Checking repo checkpoint..."
      - |
        if [ -f checkpoint.json ]; then
          if grep -q '"dev": true' checkpoint.json; then
            echo "✅ Checkpoint passed, continuing pipeline"
          else
            echo "❌ Checkpoint failed, stopping pipeline"
            exit 1
          fi
        else
          echo "❌ No checkpoint.json file found, stopping pipeline"
          exit 1
        fi

  build:
    commands:
      - echo "📦 No build step needed for static site"

  post_build:
    commands:
      - echo "🚀 Deploying static site to S3..."
      - aws s3 sync . s3://$S3_BUCKET_NAME/ --delete --exclude "checkpoint.json" --exclude "buildspec.yml"

artifacts:
  files:
    - '**/*'
